from .app import db


class Mortality_causes(db.Model):
    __tablename__ = 'main'
    index = db.Column(db.BIGINT)
    ENT_REGIS =db.Columnn(db.BIGINT)
    MUN_REGIS = db.Column(db.BIGINT)
    ENT_RESID = db.Column(db.BIGINT)
    MUN_RESID= db.Column(db.BIGINT)
    TLOC_RESID= db.Column(db.BIGINT)
    LOC_RESID = db.Column(db.BIGINT)
    ENT_OCURR = db.Column(db.BIGINT)
    MUN_OCURR= db.Column(db.BIGINT)
    TLOC_OCURR = db.Column(db.BIGINT)
    LOC_OCURR= db.Column(db.BIGINT)
    CAUSA_DEF =db.Column(db.Text)
    LISTA_MEX = db.Column(db.Text)
    SEXO = db.Column(db.BIGINT)
    EDAD = db.Column(db.BIGINT)
    DIA_OCURR = db.Column(db.BIGINT)
    MES_OCURR= db.Column(db.BIGINT)
    ANIO_OCUR = db.Column(db.BIGINT)
    DIA_REGIS = db.Column(db.BIGINT)
    MES_REGIS= db.Column(db.BIGINT)
    ANIO_REGIS = db.Column(db.BIGINT)
    DIA_NACIM= db.Column(db.BIGINT)
    MES_NACIM = db.Column(db.BIGINT)
    ANIO_NACIM= db.Column(db.BIGINT)
    OCUPACION = db.Column(db.BIGINT)
    ESCOLARIDA = db.Column(db.BIGINT)
    EDO_CIVIL = db.Column(db.BIGINT)
    PRESUNTO= db.Column(db.BIGINT)
    OCURR_TRAB = db.Column(db.BIGINT)
    LUGAR_OCUR= db.Column(db.BIGINT)
    NECROPSIA = db.Column(db.BIGINT)
    ASIST_MEDI = db.Column(db.BIGINT)
    SITIO_OCUR= db.Column(db.BIGINT)
    COND_CERT = db.Column(db.BIGINT)
    NACIONALID = db.Column(db.BIGINT)
    DERECHOHAB= db.Column(db.BIGINT)
    EMBARAZO = db.Column(db.BIGINT)
    REL_EMBA= db.Column(db.BIGINT)
    HORAS = db.Column(db.BIGINT)
    MINUTOS = db.Column(db.BIGINT)
    CAPITULO = db.Column(db.BIGINT)
    GRUPO = db.Column(db.BIGINT)
    LISTA1 = db.Column(db.BIGINT)
    GR_LISMEX = db.Column(db.BIGINT)
    VIO_FAMI= db.Column(db.BIGINT)
    AREA_UR = db.Column(db.BIGINT)
    EDAD_AGRU = db.Column(db.BIGINT)
    COMPLICARO = db.Column(db.BIGINT)
    DIA_CERT= db.Column(db.BIGINT)
    MES_CERT = db.Column(db.BIGINT)
    ANIO_CERT = db.Column(db.BIGINT)
    MATERNAS= db.Column(db.TEXT)
    LENGUA = db.Column(db.BIGINT)
    COND_ACT = db.Column(db.BIGINT)
    PAR_AGRE = db.Column(db.BIGINT)
    ENT_OCULES = db.Column(db.BIGINT)
    MUN_OCULES = db.Column(db.BIGINT)
    LOC_OCULES = db.Column(db.BIGINT)
    RAZON_M= db.Column(db.FLOAT)
    DIS_RE_OAX = db.Column(db.BIGINT)

    def __repr__(self):
        return '<Mortality_causes %r>' % (self.name)
